FROM ubuntu:14.04

RUN apt-get update; apt-get --yes install python-dev python-pip python-pandas python-sklearn openjdk-7-jdk wget

RUN mkdir -p /scripts /logs

# Install Drake
WORKDIR /scripts
RUN wget https://raw.githubusercontent.com/Factual/drake/master/bin/drake
RUN chmod a+x drake
RUN mv drake /usr/local/bin/

# Install any packages
__INSTALL_PACKAGE_STEP__

# Add the actual script that will run
__INSTALL_SCRIPT_STEP__

# Make the script the default command
__DEFAULT_CMD_STEP__